version: "3"

services:
  zsh:
    build: .
    container_name: elixir-dev
    volumes:
      - ./shared-dir:/home/nick/shared-dir
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/nick/.ssh:/home/nick/.ssh:ro
    environment:
      DISPLAY:
