version: "3"

services:
  zsh:
    # build: .
    image: nmahoney/dev
    container_name: nwm-dev
    volumes:
      - ./shared-dir:/home/nick/shared-dir
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/nick/.ssh:/home/nick/.ssh:ro
    environment:
      DISPLAY:
